hospital/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('doctors.urls')),
    path('', include('patients.urls')),
]

users/urls.py
from django.urls import path
from .views import register, login_view, forgot_view, reset_view,logout_view
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', login_view, name='login'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('password-reset/', forgot_view, name='password-reset'),
    path('reset/<str:token>/', reset_view, name='reset'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=staticfiles_urlpatterns()

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

class Address(models.Model):
    id_address = models.AutoField(primary_key=True)
    address_line = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    code_postal = models.CharField(max_length=50)
    
    class Meta:
      verbose_name = "Address"
      verbose_name_plural = "Addresses"
      
    def __str__(self):
      return self.address_line



class Users(AbstractUser):
    email = models.CharField(max_length=50,unique=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=200)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    gender_choices = (("Male", "Male"), ("Female", "Female"))
    gender = models.CharField(max_length=10, choices=gender_choices, default="not_known")
    birthday = models.DateField(null=True, blank=True)
    is_doctor = models.BooleanField(default=False)
    profile_avatar = models.ImageField(upload_to="users/profiles", blank=True, default="doctor/profiles/download.png")
    id_address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True)
    
    class Meta:
      verbose_name = "User"
      verbose_name_plural = "Users"
      
    def __str__(self):
      return self.username

class Reste_token(models.Model):
   user = models.ForeignKey(Users,on_delete=models.CASCADE)
   email = models.CharField(max_length = 50,unique=True)
   token = models.CharField(max_length = 50)

class Specialty(models.Model):
    name = models.CharField(max_length=25 , unique=True)
    description = models.TextField()
    
    class Meta:
      verbose_name = "Specialty"
      verbose_name_plural = "Specialty"
    
    def __str__(self):
      return self.name
    
class Doctors(models.Model):
  user = models.OneToOneField(Users, on_delete=models.CASCADE, primary_key=True)
  specialty = models.ForeignKey(Specialty,on_delete=models.CASCADE)
  bio = models.TextField()
  
  class Meta:
    verbose_name = "Doctor"
    verbose_name_plural = "Doctors"
    
  def __str__(self):
      return self.user.get_full_name() or self.user.username

      
class Patients(models.Model):
  user = models.OneToOneField(Users, on_delete=models.CASCADE, primary_key=True)
  insurance = models.CharField(max_length=50)
  
  class Meta:
    verbose_name = "Patient"
    verbose_name_plural = "Patients"
  
  def __str__(self):
      return self.user.get_full_name() or self.user.username

users/views.py
from django.shortcuts import render

from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model
from .models import Doctors, Patients, Address , Reste_token , Specialty
from .helpers import send_email
import uuid


Users = get_user_model()

def register(request):
  specialities = Specialty.objects.all()
  if request.method == 'POST':
    user_status = request.POST.get('user_config')
    first_name = request.POST.get('user_firstname')
    last_name = request.POST.get('user_lastname')
    profile_pic = ""

    if "profile_pic" in request.FILES:
      profile_pic = request.FILES['profile_pic']

    username = request.POST.get('user_id')
    email = request.POST.get('email')
    gender = request.POST.get('user_gender')
    birthday = request.POST.get("birthday")
    password = request.POST.get('password')
    confirm_password = request.POST.get('conf_password')
    address_line = request.POST.get('address_line')
    region = request.POST.get('region')
    city = request.POST.get('city')
    pincode = request.POST.get('pincode')

    if len(password) < 6:
      messages.error(request, 'Password must be at least 6 characters long.')
      return render(request, 'users/register.html', context={'user_config': user_status, 'user_firstname': first_name, 'user_lastname': last_name, 'user_id': username, 'email': email, 'user_gender': gender, 'address_line': address_line, 'region': region, 'city': city, 'pincode': pincode})

    if password != confirm_password:
      messages.error(request, 'Passwords do not match.')
      return render(request, 'users/register.html', context={'user_config': user_status, 'user_firstname': first_name, 'user_lastname': last_name, 'user_id': username, 'email': email, 'user_gender': gender, 'address_line': address_line, 'region': region, 'city': city, 'pincode': pincode})

    if Users.objects.filter(username=username).exists():
      messages.error(request, 'Username already exists. Try again with a different username.')
      return render(request, 'users/register.html', context={'user_config': user_status, 'user_firstname': first_name, 'user_lastname': last_name, 'user_id': username, 'email': email, 'user_gender': gender, 'address_line': address_line, 'region': region, 'city': city, 'pincode': pincode})

    address = Address.objects.create(address_line=address_line, region=region,city=city, code_postal=pincode)

    user = Users.objects.create_user(
      first_name=first_name,
      last_name=last_name,
      profile_avatar=profile_pic,
      username=username,
      email=email,
      gender=gender,
      birthday=birthday,
      password=password,
      id_address=address,
      is_doctor=(user_status == 'Doctor')
    )
      
    user.save()

    if user_status == 'Doctor':
      specialty = request.POST.get('Speciality')
      specialty_name = Specialty.objects.get(name=specialty)
      bio = request.POST.get('bio')
      doctor = Doctors.objects.create(user=user, specialty=specialty_name, bio=bio)
      doctor.save()
        
    elif user_status == 'Patient':
        insurance = request.POST.get('insurance')
        patient = Patients.objects.create(user=user, insurance=insurance)
        patient.save()

    messages.success(request, 'Your account has been successfully registered. Please login.', extra_tags='success')


  return render(request, 'users/register.html' , {'specialities':specialities})


def login_view(request):
  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(request, username=username, password=password)

    if user is not None:
      login(request, user)

      if user.is_doctor:
        return redirect('doctor_dashboard')

      elif Patients.objects.filter(user=user).exists():
        return redirect('patient_dashboard')
    else:
      messages.error(request, 'Incorrect username or password')
      
    return render(request, 'users/login.html')
  
  return render(request, 'users/login.html')


def forgot_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = Users.objects.filter(email=email)
        if user:
            token = str(uuid.uuid4())
            reset = Reste_token.objects.create(
                user=user[0],
                email=user[0].email,  
                token=token  
            )
            reset.save()
            sent = send_email(user[0].email,token)
            if sent:
                return render(request, 'users/forgot.html',context={'send_email_succes': 1})
        else:
            return render(request, 'users/forgot.html', context={'errorlogin': 1})
    return render(request, 'users/forgot.html')

def reset_view(request,token):
    if request.method == 'POST':
        reste = Reste_token.objects.filter(token=token)
        print(reste)
        if reste:
            password = request.POST.get('password')
            confirm_password = request.POST.get('conf_password')
            if len(password) < 6:
                messages.error(request, 'Password must be at least 6 characters long.')
                return render(request, 'users/reset.html', {'token': token} )
            print(password)
            print(confirm_password)
            if password != confirm_password:
                messages.error(request, 'password do not match')
                return render(request, 'users/reset.html', {'token': token} )
            user = Users.objects.filter(email=reste[0].email).first()
            if user:
                hashed_password = make_password(password)
                user.password = hashed_password
                user.save()
                reste.delete()
                return redirect('login')
            else:
                return render(request, 'users/reset.html', {'token': token , 'errorlogin':1} )
        return render(request, 'users/reset.html', {'token': token} )
    return render(request, 'users/reset.html',{'token': token})


@login_required(login_url='/login')
def logout_view(request):
    logout(request)
    return redirect('login')

templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock title %} -     Boshqaruvi</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/icon_app.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/base-style.css' %}" rel="stylesheet"/>
  </head>

  <body>
    <section class="h-100">
      <div class="container h-100">
        <div class="row justify-content-sm-center h-100">
          <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
            <div class="text-center my-5" style="height: 80px;">
              <img src="{% static 'img/logo.png' %}" alt="logo" class="img-fluid" style="max-height: 70px; max-width: 270px;" />
            </div>
            {% block content %}{% endblock content %}
            <div class="text-center my-5 text-muted">
              Mualliflik huquqi &copy; 2024 &mdash; Kasalxona Boshqaruvi
            </div>
          </div>
        </div>
      </div>
    </section>
    <script src="{% static 'js/login.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/users/forgot.html
{% extends 'users/base.html' %}

{% block title %}Parolni unutdingiz{% endblock title %}

{% block content %}
<div class="card shadow-lg">
  <div class="card-body p-5">
    {% if errorlogin %}
  <div class="alert alert-danger" role="alert">
    Noto‘g‘ri ma’lumotlar
  </div>
  {% endif %}
  {% if send_email_succes %}
      <div class="alert alert-success" role="alert">
        Elektron pochta jo‘natildi
      </div>
    {% endif %}
    <h1 class="fs-4 card-title fw-bold mb-4">Parolni unutdingiz</h1>
    <form method="POST" class="needs-validation" novalidate="" autocomplete="off">
      {% csrf_token %}
      <div class="mb-3">
        <label class="mb-2 text-muted" for="email">Elektron pochta manzili</label>
        <input id="email" type="email" class="form-control" name="email" value="" required autofocus />
        <div class="invalid-feedback">Email noto‘g‘ri</div>
      </div>

      <div class="d-flex align-items-center">
        <button type="submit" class="btn btn-primary ms-auto">
          Havola yuborish
        </button>
      </div>
    </form>
  </div>

  <div class="card-footer py-3 border-0">
    <div class="text-center">
      Parolingizni eslab qoldingizmi?
      <a href={% url 'login' %} class="text-dark">Kirish</a>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/login.html
{% extends 'users/base.html' %} 
{% block title %}Kirish Sahifasi{% endblock title %}

{% block content %}
<div class="card shadow-lg mx-auto mt-5" style="max-width: 24rem">
  <div class="card-body p-4">
    <h1 class="fs-4 card-title fw-bold mb-3 text-center">Kirish</h1>

    <form
      method="POST"
      class="needs-validation"
      novalidate=""
      autocomplete="off"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      {% if messages %}
        {% for message in messages %}
          <div
            class="alert alert-danger alert-dismissible fade show mt-3"
            role="alert"
          >
            {{ message }}
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
          </div>
        {% endfor %}
      {% endif %}

      <div class="mb-3">
        <label class="mb-2 text-muted" for="email">Foydalanuvchi ID</label>
        <input
          id="email"
          type="text"
          class="form-control"
          name="username"
          value=""
          required
          autofocus
        />
        <div class="invalid-feedback">Foydalanuvchi ID noto‘g‘ri</div>
      </div>

      <div class="mb-3">
        <div class="mb-2 w-100">
          <label class="text-muted" for="password">Parol</label>
          <a href="{% url 'password-reset' %}" class="float-end primary-color">Parolni unutdingizmi?</a>
        </div>

        <input
          id="password"
          type="password"
          class="form-control"
          name="password"
          required
        />
        <div class="invalid-feedback">Parol kiritilishi shart</div>
      </div>

      <div class="d-flex align-items-center">
        <div class="form-check">
          <label for="remember" class="form-check-label"></label>
        </div>

        <button
          type="submit"
          class="btn btn-primary ms-auto primary-color-background"
        >
          Kirish
        </button>
      </div>
    </form>
  </div>
  <div class="card-footer py-3 border-0">
    <div class="text-center">
      Hali akkauntingiz yo‘qmi?
      <a href="{% url 'register' %}" class="text-dark secondary-color">Ro‘yxatdan o‘tish</a>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_email.html
<p>Salom</p>

<p>
  Siz bu elektron pochta xabarini, {{domain}} saytida foydalanuvchi akkauntingiz uchun parolni tiklashni so‘raganingiz uchun olasiz.
</p>

<p>Iltimos, parolingizni tiklash uchun quyidagi havolani bosing:</p>

<a
  href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}"
  >bu yerga bosing</a
>

<p>Rahmat</p>
<p>kasalxona jamoasi</p>

templates/users/register.html
{% extends 'users/base.html' %}

{% block title %}Ro‘yxatdan o‘tish sahifasi{% endblock title %}

{% block content %}
<div class="card shadow-lg mx-auto mt-5" style="max-width: 34rem;">
  <div class="card-body p-4">
    <h1 class="fs-4 card-title fw-bold mb-3 text-center">Ro‘yxatdan o‘tish</h1>

    <form method="POST" class="needs-validation" novalidate="" autocomplete="off" enctype="multipart/form-data">
      {% csrf_token %}

      {% if messages %}
      {% for message in messages %}
      {% if 'success' in message.tags %}
      <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% else %}
      <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
      {% endfor %}
      {% endif %}

      <div class="mb-3">
        <label class="mb-2 text-muted" for="user_status">Holatingizni tanlang:</label>
        <select class="form-select" name="user_config" id="user_status">
          <option value="Doctor" {% if user_config=='Doctor' %}selected{% endif %}>Doktor</option>
          <option value="Patient" {% if user_config=='Patient' %}selected{% endif %}>Bemor</option>
        </select>
      </div>

      <div id="specialty_block" class="mb-3"
        style="display: {% if user_config == 'Doctor' %}block{% else %}none{% endif %}">
        <label class="mb-2 text-muted" for="specialty">Spetsializatsiya</label>
        <select name="Speciality" class="form-select" id="">
          {% for speciality in specialities %}
          <option value="{{speciality.name}}">{{speciality.name}}</option>
          {%endfor%}
        </select>
        <div class="invalid-feedback">Doktorlar uchun spetsializatsiya kerak</div>
      </div>

      <div id="bio_block" class="mb-3" style="display: {% if user_config == 'Doctor' %}block{% else %}none{% endif %}">
        <label class="mb-2 text-muted" for="bio">Biografiya</label>
        <textarea id="bio" class="form-control" name="bio" {% if user_config=='Doctor' %}required{% endif %}></textarea>
        <div class="invalid-feedback">Doktorlar uchun biografiya kerak</div>
      </div>

      <div id="insurance_block" class="mb-3"
        style="display: {% if user_config == 'Patient' %}block{% else %}none{% endif %}">
        <label class="mb-2 text-muted" for="insurance">Sug‘urta</label>
        <input id="insurance" type="text" class="form-control" name="insurance" {% if user_config=='Patient'
          %}required{% endif %} />
        <div class="invalid-feedback">Bemorlar uchun sug‘urta kerak</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="id_user">Foydalanuvchi nomi</label>
        <input id="id_user" type="text" class="form-control" name="user_id" value="{{ user_id }}" required autofocus />
        <div class="invalid-feedback">Foydalanuvchi nomi talab qilinadi</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="first_name">Ism</label>
        <input id="first_name" type="text" class="form-control" name="user_firstname" value="{{ user_firstname }}"
          required autofocus />
        <div class="invalid-feedback">Ism talab qilinadi</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="last_name">Familiya</label>
        <input id="last_name" type="text" class="form-control" name="user_lastname" value="{{ user_lastname }}" required
          autofocus />
        <div class="invalid-feedback">Familiya talab qilinadi</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="select_gender">Jins</label>
        <select class="form-select" aria-label="Default select example" name="user_gender" id="select_gender">
          <option value="Male" {% if user_gender=='Male' %}selected{% endif %}>Erkak</option>
          <option value="Female" {% if user_gender=='Female' %}selected{% endif %}>Ayol</option>
        </select>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="birthday">Tug‘ilgan sana</label>
        <input id="birthday" type="date" class="form-control" name="birthday" value="{{ birthday }}" required />
        <div class="invalid-feedback">Tug‘ilgan sana noto‘g‘ri</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="email">E-mail manzili</label>
        <input id="email" type="email" class="form-control" name="email" value="{{ email }}" required />
        <div class="invalid-feedback">E-mail noto‘g‘ri</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="password">Parol</label>
        <input id="password" type="password" class="form-control" name="password" required />
        <div class="invalid-feedback">Parol talab qilinadi</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="conf__password">Parolni tasdiqlash</label>
        <input id="conf__password" type="password" class="form-control" name="conf_password" required />
        <div class="invalid-feedback">Parolni tasdiqlash talab qilinadi</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="AddressLine">Manzil</label>
        <input id="AddressLine" type="text" class="form-control mb-2" name="address_line" value="{{ address_line }}"
          placeholder="Manzil" required autofocus />
        <input id="Region" type="text" class="form-control mb-2" name="region" value="{{ region }}"
          placeholder="Viloyat" required autofocus />
        <input id="City" type="text" class="form-control mb-2" name="city" value="{{ city }}" placeholder="Shahar"
          required autofocus />
        <input id="Pincode" type="text" class="form-control" name="pincode" value="{{ pincode }}"
          placeholder="Pochta indeksi" required autofocus />
        <div class="invalid-feedback">Manzil talab qilinadi</div>
      </div>

      <div class="mb-3 col-12 col-md-12">
        <label for="pic" class="form-label text-muted">Profil rasmi</label>
        <input type="file" class="form-control p-3" name="profile_pic" id="pic" required>
      </div>

      <p class="form-text text-muted mb-3">
        Ro‘yxatdan o‘tish orqali siz bizning shartlarimiz va sharoitlarimizga rozilik bildirasiz.
      </p>

      <div class="align-items-center d-flex">
        <button type="submit" class="btn btn-primary ms-auto primary-color-background">
          Ro‘yxatdan o‘tish
        </button>
      </div>
    </form>
  </div>
  <div class="card-footer py-3 border-0">
    <div class="text-center">
      Allaqachon akkauntingiz bormi?
      <a href="{% url 'login' %}" class="text-dark secondary-color">Kirish</a>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    toggleFields();

    document.getElementById('user_status').addEventListener('change', function () {
      toggleFields();
    });

    function toggleFields() {
      var userConfig = document.getElementById('user_status').value;
      var specialtyBlock = document.getElementById('specialty_block');
      var bioBlock = document.getElementById('bio_block');
      var insuranceBlock = document.getElementById('insurance_block');

      if (userConfig === 'Doctor') {
        specialtyBlock.style.display = 'block';
        bioBlock.style.display = 'block';
        insuranceBlock.style.display = 'none';
      } else if (userConfig === 'Patient') {
        specialtyBlock.style.display = 'none';
        bioBlock.style.display = 'none';
        insuranceBlock.style.display = 'block';
      }
    }
  });
</script>

{% endblock content %}

templates/users/reset.html
{% extends 'users/base.html' %} 
{% block content %}
<div class="card shadow-lg">
  <div class="card-body p-5">
    <h1 class="fs-4 card-title fw-bold mb-4">Parolni tiklash</h1>
    <form
      method="POST"
      class="needs-validation"
      novalidate=""
      autocomplete="off"
    >
      {% csrf_token %}
      <div class="mb-3">
        <div class="card-body p-5">
          {% if errorlogin %}
            <div class="alert alert-danger" role="alert">
              Noto'g'ri ma'lumotlar
            </div>
          {% endif %}
        <label class="mb-2 text-muted" for="password">Yangi parol</label>
        <input
          id="password"
          type="password"
          class="form-control"
          name="password"
          value=""
          required
          autofocus
        />
        <div class="invalid-feedback">Parol talab qilinadi</div>
      </div>

      <div class="mb-3">
        <label class="mb-2 text-muted" for="password-confirm">Parolni tasdiqlash</label>
        <input
          id="password-confirm"
          type="password"
          class="form-control"
          name="conf_password"
          required
        />
        <div class="invalid-feedback">Yangi parolingizni tasdiqlang</div>
      </div>

      <div class="d-flex align-items-center">
        <button type="submit" class="btn btn-primary ms-auto">
          Parolni tiklash
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}